{
  "full_first_name": "Grace",
  "full_middle_name": "Nabirye",
  "full_surname": "Kintu",
  "other_names": "Gracie",
  "date_of_birth": "1997-11-23",
  "gender": "Female",
  "nationality": "Ugandan",
  "mobile_phone_1": "+256781234567",
  "mobile_phone_2": "+256752345678",
  "home_phone_1": "+256414654321",
  "home_phone_2": "+256392654321",
  "email": "atwanzirebroz@gmail.com",
  "current_location": "Jinja, Uganda",
  "permanent_home_address": "Iganga, Eastern Uganda",
  "year_joined_jonahs": 2011,
  "house": "ST. JOHNMARY HOUSE",
  "classes_attended": "S1, S2, S3, S4, S5, S6",
  "year_left_jonahs": 2016,
  "sat_uce": true,
  "sat_uace": true,
  "uce_class_year": 2014,
  "uace_class_year": 2016,
  "mentorship_career_guidance": true,
  "skill_sharing": false,
  "networking": true,
  "fundraisers": true,
  "event_planning": false,
  "cohort_mobilisation": true,
  "volunteering": false,
  "financial_support": false,
  "charitable_outreach_programs": true,
  "alumni_sports_league": false,
  "alumni_dinner": true,
  "events_at_school": true,
  "all_get_together_events": false,
  "consent_given": true
}
