# Generated by Django 5.2 on 2025-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_executiveteammember_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiveteammember',
            name='rank',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
