# Generated by Django 5.2 on 2025-05-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_executiveteammember_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executiveteammember',
            options={'ordering': ['rank']},
        ),
        migrations.AddField(
            model_name='executiveteammember',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
