# Generated by Django 5.2 on 2025-05-30 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_executiveteammember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountapplication',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
